"""frontend：Python 地理业务代码 → Geo-IR。"""

from .analyzer import (
    DIAG_ARITY,
    DIAG_BACKEND_MISSING,
    DIAG_DYNAMIC_CONTROL_FLOW,
    DIAG_NOT_TRACEABLE,
    DIAG_PLAINTEXT_UTILITY,
    DIAG_PROTOCOL_UNSUPPORTED,
    DIAG_SPU_UNSUPPORTED,
    DIAG_STATIC_ASSERT,
    DIAG_UNKNOWN_CALL,
    DIAG_UNRESOLVED_INPUT,
    DIAG_UNSUPPORTED_GEO_OP,
    Diagnostic,
    FrontendAnalyzer,
    FrontendError,
    FunctionInfo,
    ParseResult,
    parse_file,
    parse_source,
)
from .dialect import (
    GEO_DIALECT,
    PLAINTEXT_UTILITIES,
    DialectEntry,
    dialect_ops,
    is_plaintext_utility,
    resolve_dialect,
)

__all__ = [
    "DIAG_ARITY",
    "DIAG_BACKEND_MISSING",
    "DIAG_DYNAMIC_CONTROL_FLOW",
    "DIAG_NOT_TRACEABLE",
    "DIAG_PLAINTEXT_UTILITY",
    "DIAG_PROTOCOL_UNSUPPORTED",
    "DIAG_SPU_UNSUPPORTED",
    "DIAG_STATIC_ASSERT",
    "DIAG_UNKNOWN_CALL",
    "DIAG_UNRESOLVED_INPUT",
    "DIAG_UNSUPPORTED_GEO_OP",
    "Diagnostic",
    "DialectEntry",
    "FrontendAnalyzer",
    "FrontendError",
    "FunctionInfo",
    "GEO_DIALECT",
    "ParseResult",
    "PLAINTEXT_UTILITIES",
    "dialect_ops",
    "is_plaintext_utility",
    "parse_file",
    "parse_source",
    "resolve_dialect",
]
