"""Geo-IR：面向地理业务的中间表示。

对外只暴露四类东西：
    GeoType / Sensitivity          —— 类型与敏感级别
    GeoEntity / GeoValue           —— 值
    GeoOperation / GeoProgram      —— 算子与程序
    GeoRelation                    —— 关系输出
    encode_grid_code / toff_of     —— 与本课题格网、时间轴口径对齐的编码工具
"""

from .geosot import (
    HEIGHT_LAYER_BITS,
    HEIGHT_LAYER_MAX,
    MAX_LEVEL,
    R0,
    THETA0,
    cell_deg,
    cells_per_deg,
    height_cell,
    height_index,
    height_layer_bits,
    height_layer_bounds,
    height_layer_count,
    height_layer_fits,
    height_layer_lower,
    height_layers,
    max_supported_height,
    validate_height_layer,
)
from .operations import SUPPORTED_OPS, GeoOperation, GeoProgram
from .render import (
    render_operations_table,
    render_program,
    render_relations,
    render_table,
)
from .types import (
    CRYPTO_REQUIRED_LEVEL,
    GEOMETRIC_TYPES,
    SENSITIVITY_ORDER,
    TEMPORAL_TYPES,
    GeoType,
    Sensitivity,
    max_sensitivity,
    requires_crypto,
    sensitivity_rank,
)
from .values import (
    DT_CODE_MIN,
    GRID_CODE_BITS,
    GRID_CODE_LAYOUT,
    GRID_CODE_LAYOUT_ID,
    GRID_CODE_LAYOUT_VERSION,
    MAX_ENCODABLE_LEVEL,
    grid_code_layout_manifest,
    grid_code_height_interval,
    height_band_codes,
    layer_codes_for_height,

    GRID_CODE_BYTES,
    GRID_CODE_WIDTH,
    LT_MAX,
    TIME_TREE_ORIGIN,
    GeoEntity,
    GeoRelation,
    GeoValue,
    codes_to_hex,
    decode_grid_code,
    encode_grid_code,
    parse_hex_codes,
    relation_from_operation,
    toff_of,
)

__all__ = [
    "CRYPTO_REQUIRED_LEVEL",
    "DT_CODE_MIN",
    "HEIGHT_LAYER_BITS",
    "HEIGHT_LAYER_MAX",
    "MAX_ENCODABLE_LEVEL",
    "MAX_LEVEL",
    "R0",
    "THETA0",
    "cell_deg",
    "cells_per_deg",
    "grid_code_height_interval",
    "grid_code_layout_manifest",
    "height_band_codes",
    "height_cell",
    "height_index",
    "height_layer_bits",
    "height_layer_bounds",
    "height_layer_count",
    "height_layer_fits",
    "height_layer_lower",
    "height_layers",
    "layer_codes_for_height",
    "max_supported_height",
    "GEOMETRIC_TYPES",
    "GRID_CODE_BITS",
    "GRID_CODE_BYTES",
    "GRID_CODE_LAYOUT",
    "GRID_CODE_LAYOUT_ID",
    "GRID_CODE_LAYOUT_VERSION",
    "GRID_CODE_WIDTH",
    "GeoEntity",
    "GeoOperation",
    "GeoProgram",
    "GeoRelation",
    "GeoType",
    "GeoValue",
    "LT_MAX",
    "SENSITIVITY_ORDER",
    "SUPPORTED_OPS",
    "Sensitivity",
    "TEMPORAL_TYPES",
    "TIME_TREE_ORIGIN",
    "codes_to_hex",
    "decode_grid_code",
    "encode_grid_code",
    "max_sensitivity",
    "parse_hex_codes",
    "relation_from_operation",
    "render_operations_table",
    "render_program",
    "render_relations",
    "render_table",
    "requires_crypto",
    "sensitivity_rank",
    "toff_of",
    "validate_height_layer",
]
