"""SPU 后端：能力探测与模拟执行。

`run_spu_simulation` 是本层对外的主入口。
"""

from .capability import (
    FIELD_BITS,
    OP_HLO_PRIMITIVES,
    OP_HLO_PRIMITIVES_BY_STRATEGY,
    OP_PRIMITIVES,
    PROTOCOL_MIN_WORLD_SIZE,
    SPU_ADAPTED_HLO_PRIMITIVES,
    SPU_ADAPTED_PRIMITIVES,
    SPU_EXPENSIVE_HLO_PRIMITIVES,
    SPU_FIELDS,
    SPU_JAX_PIN,
    SPU_JAX_PRIVATE_DEPS,
    SPU_PROTOCOLS,
    SPU_PROTOCOLS_WITHOUT_CRYPTO,
    CapabilityReport,
    JaxProbe,
    OpCapability,
    SpuProbe,
    check_capabilities,
    check_operation_capability,
    normalize_field,
    normalize_protocol,
    platform_can_run_spu,
    probe_jax,
    probe_platform,
    probe_spu,
    protocol_min_world_size,
)
from .cost_baseline import MeasuredComm, measured_comm_table
from .runtime import SpuRunResult, TripleResult, run_spu_simulation
from .benchmark import (
    EXPECT_DEVIATION,
    MIXED_STATUS,
    MPC_BENCHMARK_OPS,
    MpcBenchmarkCase,
    format_summary,
    predicted_bit_width,
    predicted_cost,
    reconcile_bit_width,
    run_benchmark_case,
    summarize_repeats,
    run_benchmark_cases,
    standard_cases,
    temporal_ab_cases,
    unexpected_records,
    write_benchmark_csv,
    write_benchmark_json,
)

__all__ = [
    "CapabilityReport",
    "EXPECT_DEVIATION",
    "FIELD_BITS",
    "JaxProbe",
    "MPC_BENCHMARK_OPS",
    "MeasuredComm",
    "MpcBenchmarkCase",
    "OP_HLO_PRIMITIVES",
    "OP_HLO_PRIMITIVES_BY_STRATEGY",
    "OP_PRIMITIVES",
    "OpCapability",
    "PROTOCOL_MIN_WORLD_SIZE",
    "SPU_ADAPTED_HLO_PRIMITIVES",
    "SPU_ADAPTED_PRIMITIVES",
    "SPU_EXPENSIVE_HLO_PRIMITIVES",
    "SPU_FIELDS",
    "SPU_JAX_PIN",
    "SPU_JAX_PRIVATE_DEPS",
    "SPU_PROTOCOLS",
    "SPU_PROTOCOLS_WITHOUT_CRYPTO",
    "SpuProbe",
    "SpuRunResult",
    "TripleResult",
    "check_capabilities",
    "check_operation_capability",
    "normalize_field",
    "normalize_protocol",
    "platform_can_run_spu",
    "predicted_bit_width",
    "predicted_cost",
    "probe_jax",
    "probe_platform",
    "measured_comm_table",
    "probe_spu",
    "protocol_min_world_size",
    "reconcile_bit_width",
    "run_benchmark_case",
    "run_benchmark_cases",
    "run_spu_simulation",
    "format_summary",
    "MIXED_STATUS",
    "summarize_repeats",
    "standard_cases",
    "temporal_ab_cases",
    "unexpected_records",
    "write_benchmark_csv",
    "write_benchmark_json",
]
